create table if not exists role
(
    date_created timestamp(6),
    id           bigint generated by default as identity
        primary key,
    name         varchar(255) not null
        unique,
    status       varchar(255)
        constraint role_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'REMOVE'::character varying])::text[]))
);

insert into role (name, status)
values ('USER', 'ACTIVE');