create table if not exists users
(
    date_created timestamp(6),
    id           bigint generated by default as identity
        primary key,
    role_id      bigint not null
        constraint fk4qu1gr772nnf6ve5af002rwya
            references role,
    email        varchar(255),
    name         varchar(255),
    password     varchar(255)
);