create table if not exists refresh_token
(
    date_created timestamp(6),
    id           bigint generated by default as identity
        primary key,
    user_id      bigint not null
        constraint fkjtx87i0jvq2svedphegvdwcuy
            references users,
    value        varchar(255)
);