create table if not exists daily_open_close
(
    after_hours numeric(38, 2),
    close       numeric(38, 2),
    date_from   date,
    high        numeric(38, 2),
    low         numeric(38, 2),
    open        numeric(38, 2),
    pre_market  numeric(38, 2),
    id          bigint generated by default as identity
        primary key,
    status      varchar(255),
    symbol      varchar(255),
    volume      varchar(255)
);
