create table if not exists user_daily_open_close_history
(
    daily_open_close_id bigint not null
        constraint fkdfhe2oy8krrmbstad5qkugfww
            references daily_open_close,
    date_created        timestamp(6),
    id                  bigint generated by default as identity
        primary key,
    user_id             bigint not null
        constraint fkfaa0beqx9rac06vitvd7tn4cv
            references users
);
